export const GLOBALS = {
    ALL_COUNTRIES: 'Overall Worldwide Totals',
    LANDSCAPE_WIDTH: 900,
    LANDSCAPE_HEIGHT: 425,
    PORTRAIT_WIDTH: 450,
    PORTRAIT_HEIGHT: 500,
    THRESHOLD: 15000,
    US_THRESHOLD: 5000,
    US_KEY: 'US',
    TOGGLE_BTN_SHOW_MORE: 'Show Details',
    TOGGLE_BTN_HIDE: 'Hide Details',
    DROPDOWN_MAPPING: {
        US: 'United States',
    },
    DATA_TIMEOUT: 2500,
    REFRESH_INTERVAL: 60000,
    ANIMATION_DELAY: 250,
};
